# Generated by Django 3.2.10 on 2021-12-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО студента')),
                ('user_id', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='ID студента')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('score', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Баллы студента')),
                ('normalized_score', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Баллы студента')),
            ],
            options={
                'verbose_name': 'Спортивное мероприятие',
                'verbose_name_plural': 'Спортивные мероприятия',
            },
        ),
        migrations.AlterModelOptions(
            name='studentsevent',
            options={'verbose_name': 'Мероприятие на проверку', 'verbose_name_plural': 'Мероприятия на проверку'},
        ),
        migrations.AddField(
            model_name='studentsevent',
            name='user_id',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='ID студента'),
            preserve_default=False,
        ),
    ]
