# Generated by Django 3.2.10 on 2021-12-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211222_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsevent',
            name='checked',
            field=models.CharField(default='Проверяется', max_length=20, verbose_name='Статус проверки'),
        ),
    ]
