# Generated by Django 3.2.10 on 2021-12-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_studentsevent_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsevent',
            name='user_id',
            field=models.DecimalField(decimal_places=0, default=-1, max_digits=10, verbose_name='ID студента'),
        ),
    ]
