# Generated by Django 3.2.10 on 2021-12-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_sportevent_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportevent',
            name='title',
        ),
    ]
