# Generated by Django 3.2.10 on 2021-12-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_name_sportevent_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('patronymic', models.CharField(max_length=25, verbose_name='Отчество')),
                ('likes', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Лайки')),
                ('dislikes', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Лайки')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
