# Generated by Django 3.2.10 on 2021-12-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
