# Generated by Django 3.2.10 on 2021-12-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='ID студента')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('likes', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Лайки')),
                ('dislikes', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Лайки')),
            ],
        ),
    ]
