# Generated by Django 3.2.10 on 2021-12-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_studentsevent_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='ФИО студента')),
                ('user_id', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='ID студента')),
                ('score', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Баллы студента')),
                ('normalized_score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Пронормированные баллы студента')),
            ],
            options={
                'verbose_name': 'Творческое мероприятие',
                'verbose_name_plural': 'Творческие мероприятия',
            },
        ),
        migrations.CreateModel(
            name='RatingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='ФИО студента')),
                ('user_id', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='ID студента')),
                ('score', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Баллы студента')),
                ('normalized_score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Пронормированные баллы студента')),
            ],
            options={
                'verbose_name': 'Общий рейтинг',
                'verbose_name_plural': 'Общий рейтинг',
            },
        ),
        migrations.CreateModel(
            name='ScienceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='ФИО студента')),
                ('user_id', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='ID студента')),
                ('score', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Баллы студента')),
                ('normalized_score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Пронормированные баллы студента')),
            ],
            options={
                'verbose_name': 'Научное мероприятие',
                'verbose_name_plural': 'Научные мероприятия',
            },
        ),
        migrations.CreateModel(
            name='StudiesEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='ФИО студента')),
                ('user_id', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='ID студента')),
                ('score', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Баллы студента')),
                ('normalized_score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Пронормированные баллы студента')),
            ],
            options={
                'verbose_name': 'Учебное мероприятие',
                'verbose_name_plural': 'Учебные мероприятия',
            },
        ),
    ]
