# Generated by Django 3.2.10 on 2021-12-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_creativeevent_ratingtable_scienceevent_studiesevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingtable',
            name='place',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Место в рейтинге'),
        ),
    ]
